### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by smspillaz** [nmichlo/disent#2]
Hi! I just wanted to leave a note to say that I'm doing some work on disentanglement at the moment and this repository has been super helpful (not to mention that I think you provide a really good example of how to use frameworks like hydra and pytorch-lightning).

Not sure if you're planning on taking contributions right now, since you did mention that this work was for your Master Thesis and that's already hard enough as is, but if you want, I can throw a couple of PRs your way.

**Comment by nmichlo** [comment]
Hi! Thank you very much for your kind words.

I am aiming to finish in the next month, so I might not have much time to review code until then but contributions are more than welcome, especially if they add new frameworks or datasets, or fix any of the mistakes in existing ones.
