### ISSUE TITLE
[Q]: Command to run with defaults?

### ISSUE THREAD

**Issue by cianeastwood** [nmichlo/disent#23]
Hi there,

What's the simplest way to train a VAE on cars3d with all the default settings? Is there a single command that does this, using all the yaml config files? E.g. cars3d needs to be downsampled to 64x64, and this is specified in its yaml file. Not very familiar with Hydra, so I'm not sure how to automatically load the yaml config files.

Thanks in advance, and for providing this great framework!

**Comment by nmichlo** [comment]
Hi!

This simplest way would be to clone the repo:
1. change your working directory to the root:
  ```bash
  cd disent
  ```
2. install the requirements 
  ```bash
  pip3 install requirements.txt
  pip3 install requirements-experiment.txt
  ```
3. run the experiment
   Unfortunately I see there is a config bug left over from research code that I am currently trying to extract into a separate project, meaning the general run settings are wrong. I have added a marker to fix this for the next release of dissent, and the command line options that being with `run_*` you should be able to remove then.
  ```bash
  PYTHONPATH=. python3 experiment/run.py framework=betavae dataset=cars3d framework.beta=0.01 \
  run_location=local_cpu run_launcher=local run_logging=none  # config bug workaround
  ```

-------

Definitely need to add this to the docs! Improvements to those are in the roadmap!

**Comment by nmichlo** [comment]
This has been fixed in 5695747c1e94420c024f1505d9b8a4b3c81ad610 release v0.3.4

The simplest command should now be:

```bash
PYTHONPATH=. python3 experiment/run.py framework=betavae dataset=cars3d
```

or adjusting beta:

```bash
PYTHONPATH=. python3 experiment/run.py framework=betavae dataset=cars3d framework.beta=0.01
```

**Comment by cianeastwood** [comment]
This is fantastic!! Thank you for addressing this so quickly and thoroughly – appreciate it! The simple command really helps usability :)

**Comment by nmichlo** [comment]
No problem, glad to help!
