### ISSUE TITLE
[BUG]: Automatic downloads not working for MPI3D and dSprites

### ISSUE THREAD

**Issue by JohannesAck** [nmichlo/disent#31]
**Describe the bug**
The downloads for MPI3D and dSprites do not work automatically

**To Reproduce**
```
from disent.dataset.data import Mpi3dData
data = Mpi3dData(in_memory=True)
```
Leads to
```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\[...]\\data\\dataset\\mpi3d_realistic\\mpi3d_realistic.npz'
```

**Expected behaviour**
It would be nice if the datasets were downloaded automatically, as they are for XYSquares.

Other than that thanks a lot for the library, very helpful!

**Comment by nmichlo** [comment]
Interesting. I have not extensively tested this the download functionality on windows. Something might be wrong with the path handling functionality.

I’ll work on adding some basic tests for this when I get a chance.

As a work around, are you able to manually download the files into the directory it wants?

**Comment by nmichlo** [comment]
I noticed the color and shape MPI3D ground-truth factors were wrong due to a data loading error.

If you are still using MPI3D, please use `disent==0.6.0`, I have fixed this problem.

Are you still having the data preparation error?

**Comment by nmichlo** [comment]
I am closing this issue for now. If it is still a problem, please don't hesitate to re-open this issue!
