### ISSUE TITLE
Averaging in AdaGVAE

### ISSUE THREAD

**Issue by Confusezius** [nmichlo/disent#32]
Great work with this repository!

A quick note: In the GVAE averaging operation, I assume that

https://github.com/nmichlo/disent/blob/d3aa2d30194735d13fb700ad9844e60d742ab914/disent/frameworks/vae/_weaklysupervised__adavae.py#L238

is supposed to be 

```
ave_mean = 0.5 * (d0_posterior.mean + d1_posterior.mean)
```

right?

**Comment by nmichlo** [comment]
Oh goodness, yes. I don’t know how I let this regression slip through.

Would you like to submit a PR with the change, I’ll happily merge it?

**Comment by nmichlo** [comment]
Fixed: https://github.com/nmichlo/disent/releases/tag/v0.5.1
